version: '3.8'
services:
  discoveryserver:
    build: ./DiscoveryServer
    container_name: discoveryserver
    ports:
      - "8761:8761"
    networks:
      - spring-net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8761/actuator/health || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 40s

  configserver:
    build: ./ConfigServer
    container_name: configserver
    ports:
      - "8888:8888"
    networks:
      - spring-net
    depends_on:
      discoveryserver:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8888/actuator/health || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 40s

  # auth-service:
  #   build: ./auth-service
  #   container_name: auth-service
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=dev
  #   networks:
  #     - spring-net
  #   depends_on:
  #     configserver:
  #       condition: service_healthy
  #     discoveryserver:
  #       condition: service_healthy

  product-service:
    build: ./ProductService
    container_name: product-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - spring-net
    depends_on:
      configserver:
        condition: service_healthy
      discoveryserver:
        condition: service_healthy

  # cart-service:
  #   build: ./CartService
  #   container_name: cart-service
  #   ports:
  #     - "8085:8085"
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=dev
  #   networks:
  #     - spring-net
  #   depends_on:
  #     configserver:
  #       condition: service_healthy
  #     discoveryserver:
  #       condition: service_healthy

  # order-service:
  #   build: ./OrderService
  #   container_name: order-service
  #   ports:
  #     - "8083:8083"
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=dev
  #   networks:
  #     - spring-net
  #   depends_on:
  #     configserver:
  #       condition: service_healthy
  #     discoveryserver:
  #       condition: service_healthy

  # user-service:
  #   build: ./UserService
  #   container_name: user-service
  #   ports:
  #     - "8084:8084"
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=dev
  #   networks:
  #     - spring-net
  #   depends_on:
  #     configserver:
  #       condition: service_healthy
  #     discoveryserver:
  #       condition: service_healthy

  # api-gateway:
  #   build: ./API-Gateway
  #   container_name: api-gateway
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=dev
  #   networks:
  #     - spring-net
  #   depends_on:
  #     configserver:
  #       condition: service_healthy
  #     discoveryserver:
  #       condition: service_healthy

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - spring-net
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - product-service
      # - auth-service
      # - cart-service
      # - order-service
      # - user-service
      # - api-gateway

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - spring-net
    depends_on:
      - prometheus

networks:
  spring-net:
    driver: bridge
