version: '3.8'
services:
  # Eureka Server
  discoveryserver:
    build: ./DiscoveryServer
    container_name: discoveryserver
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8761/actuator/health || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 40s

  # Config Server
  configserver:
    build: ./ConfigServer
    container_name: configserver
    ports:
      - "8888:8888"
    depends_on:
      discoveryserver:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8888/actuator/health || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 40s

  # Auth Service
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      configserver:
        condition: service_healthy
      discoveryserver:
        condition: service_healthy
      
    

  # Product Service
  product-service:
    build: ./ProductService
    container_name: product-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      configserver:
        condition: service_healthy
      discoveryserver:
        condition: service_healthy

  # Cart Service
  cart-service:
    build: ./CartService
    container_name: cart-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      configserver:
        condition: service_healthy
      discoveryserver:
        condition: service_healthy

  # Order Service
  order-service:
    build: ./OrderService
    container_name: order-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      configserver:
        condition: service_healthy
      discoveryserver:
        condition: service_healthy

  # User Service
  user-service:
    build: ./UserService
    container_name: user-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      configserver:
        condition: service_healthy
      discoveryserver:
        condition: service_healthy

  # API Gateway
  api-gateway:
    build: ./API-Gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      configserver:
        condition: service_healthy
      discoveryserver:
        condition: service_healthy

  # Prometheus
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - auth-service
      - product-service
      - cart-service
      - order-service
      - user-service
      - api-gateway

  # Grafana
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
